### ISSUE TITLE
Warning "Multiple definitions for term ..."

### ISSUE THREAD

**Issue by docnux** [nittka/terminology#22]
Hello,

at first I have to thank you for your very interesting approach to terminology management. I decided to go this way and started to fill the "database".

A request:
The warning concerning "Multiple definitions for term" is a great thing to avoid duplicates ... but:
It is also triggered when the same term shows up in different languages within the same entry.
I would really prefer the checker to check within languages only.

Best regards,
Detlef.

**Comment by nittka** [comment]
Thanks for the feedback. I will check whether relaxing this validation would have other side effects.
Note that you can suppress this warning by annotating the term with "@DuplicateOK" (invoke code completion immediately before the Term keyword).

**Comment by nittka** [comment]
The duplicate term warning (level is configurable on the Terminology preference page) will be raised only for terms within the same language.
This fix will be available starting in version 1.1.2. However, I'd like to wait a bit before releasing a new version... Maybe you find further issues; feedback is very much appreciated.

**Comment by docnux** [comment]
... just would like to drop a great "Thanks!" for your prompt reply. This is Open Source at its best.
(I have another little suggestion ... will open another call.)
