### ISSUE TITLE
Speed-up parameter selection after keyword insertion

### ISSUE THREAD

**Issue by docnux** [nittka/terminology#23]
Just a suggestion for a lean entry process:
When I user ctrl-space for inserting a keyword like "Products", I have to enter a space manually before I can use ctrl-space to select one of the predefined products.
It would be nice if the keyword would be followed by the (syntactically required) space automatically.

**Comment by nittka** [comment]
Do you use the code templates mechanism? There are default templates for entry and term shipped with the plugin. You should see these proposals when you invoke code completion at a position where an entry/term is valid (you then see at least two suggestions - one with the keyword, one with the template). Choose the template and you will find most of the entry/term structure already present and with tab you can navigate to fields to be filled.

Why am I telling you this... Templates make the entry process even faster and they can be customized by you (Preferences->Terminology->Templates), you can even add your own templates which I would strongly recommend.

For your above use case, you would not have to choose the Product keyword but provide several templates for your most common product combinations, e.g. 
p1(codecompletion)  inserts Products product1, product2, product3(+new line and indentation)
p2(codecompletion) inserts Products anotherProduct

So using this mechanism you generally don't need automatic white space after a keyword. Note also that it is the standard behaviour of eclipse text editors to *not* insert white spaces after keywords upon code completion. It is possible to do so but it would be contrary to the user expectation within the eclipse ecosystem...

If you have problems with defining/using templates, please let me know. I would try to improve the wiki documentation.

**Comment by docnux** [comment]
Yes, I use templates.
However, the "entry" template does not contain the "Customers" item, which is OK for me, as I need it seldomly.
When I need it, I set the cursor in the line after "Usage" and hit ctrl-space. This offers the "Customers" item to me which I choose. But then I stumble into the little speed-brake. I would like to select one of the customers from the ctrl-space-list immediately - but I can't. I have to type a space before ctrl-space works for selcting the customer from the list.
I hope I could explain the point in an understandable way.
But again: This is definitely no major problem but a fine tuning wish.

**Comment by docnux** [comment]
Sorry inadvertently closed the call.

**Comment by nittka** [comment]
Please make use of defining your own templates or modifying the existing ones!  E.g. you could copy the entry template as "customerEntry" and simply add a line for the customer.
Alternatively create a customer template with context "Keyword Customers" in both cases the relevant template code should be something like

Customers ${Customers:CrossReference('Term.customers')}

If the customer lists are often the same, create a template for each one, so that you only need to choose the list rather than choosing every single customer again.

**Comment by nittka** [comment]
I have added a detailed example for defining templates in the wiki 

https://github.com/nittka/terminology/wiki/Features#template-example

This approach to the issue outperforms the proposed change and does not break the default eclipse behaviour of code completion - which I am extremely reluctant to implement (i.e. won't).

I am sure, the time you spend playing around, trying out and fine tuning your own templates will pay off very quickly.
