### ISSUE TITLE
Validation for "missing preferred term for language"

### ISSUE THREAD

**Issue by docnux** [nittka/terminology#25]
Here's a behaviour which could be optimized IMHO:

The check for "missing preferred term for language" complains also when there is no term for the language at all.
I would prefer the following behaviour:
If there is any term for this language in the entry, then check whether there is one "preferred" one. Should there be no term for this language: Ignore this test.

Reason:
I really like to know that I forgot to define one term as "preferred". But many entries don't have terms for language xyz yet. There I get bombarded with check failures.

... don't know whether this can be realized ...

**Comment by nittka** [comment]
In the current implementation you can already suppress the warning using a `@MissingPreferredTermOK` annotation (followed by a list of languages that should not cause an issue) on the entry. See https://github.com/nittka/terminology/blob/master/sample.terminology/Example_ctrl.terms#L45 for an example.

I agree that this is quite cumbersome if you have many entries where languages are intentionally missing. Using an appropriate template, you can quickly enter such entries, but you still have the noise of the additional annotation in the file

I will check whether an additional preference parameter "raise missing preferred term issue only if any term for the language is present" would make sense. If so enabling or disabling it should lead to the desired behaviour. If enabled, you still get warnings for existing languages without having to use the annotation for missing ones.

**Comment by docnux** [comment]
Sounds great!

**Comment by nittka** [comment]
An additional preference option allows to globally disable raising issues for missing preferred terms in case the language is not used at all within an entry. The default value is such that it does not modify the previous behaviour.

This fix will be available starting in version 1.1.2.

**Comment by nittka** [comment]
@docnux: You can use the temporary(?) quick and dirty snapshot update site located at
http://www.nittka.de/download/terminology
for trying out the new features. I don't know how you installed your current version...
* Help->Install new software
* Add-Button using the above URL
* If you see a "There are no categorized items" message, uncheck the "Group items by category" option at the bottom
* Choose the Terminology-feature (version 1.1.2.xxx)

This is not an official update site or version, but a preview allowing you to evaluate whether the changes made meet your requirements (and already use them).

**Comment by docnux** [comment]
Will sure check that as soon as I am back at work.
Thanks! This is open source at its best.

**Comment by docnux** [comment]
... took me very long to come back to terminology work ...
I just installed and checked the new feature. Works great and exactly as expected, thanks!

**Comment by nittka** [comment]
Thanks for the feedback.
