### ISSUE TITLE
Question - SBVR

### ISSUE THREAD

**Issue by magick93** [nittka/terminology#26]
Hi

Quick question - is this dsl based on the SBVR metamodel?

**Comment by nittka** [comment]
The short answer is no. The DSLs metamodel is much more limited (see the Wiki for human readable background and https://github.com/nittka/terminology/blob/master/de.itemis.tooling.terminology/src/de/itemis/tooling/terminology/Terminology.xtext for the technical implementation of the syntax and the metamodel). However, the two are not completely unrelated (from what I saw glancing over info on SBVR). The DSL is *concept* centered. A concept may have different "names" - terms - depending on the context in which it is used. The project is the attempt to be more helpful that an spread sheet word list (too little structure) and a full blown terminology management system (too complicated, too expensive, too many unused features). It is much closer to the spread sheet version but with essential features missing there. If the DSL is expressive enough for your use case, custom exporters are a way to get the terminology expressed using the DSL into other systems...

A longer, more detailed answer requires more time... if you need it.
